const countryDetailsTestData = [
  {
    date: '2022-01-01',
    localName: 'Yılbaşı',
    name: "New Year's Day",
    countryCode: 'TR',
    fixed: true,
    global: true,
    counties: null,
    launchYear: null,
    types: [
      'Public',
    ],
  },
  {
    date: '2022-04-23',
    localName: 'Ulusal Egemenlik ve Çocuk Bayramı',
    name: "National Independence & Children's Day",
    countryCode: 'TR',
    fixed: true,
    global: true,
    counties: null,
    launchYear: null,
    types: [
      'Public',
    ],
  },
  {
    date: '2022-05-01',
    localName: 'İşçi Bayramı',
    name: 'Labour Day',
    countryCode: 'TR',
    fixed: true,
    global: true,
    counties: null,
    launchYear: null,
    types: [
      'Public',
    ],
  },
  {
    date: '2022-05-19',
    localName: "Atatürk'ü Anma, Gençlik ve Spor Bayramı",
    name: 'Atatürk Commemoration & Youth Day',
    countryCode: 'TR',
    fixed: true,
    global: true,
    counties: null,
    launchYear: null,
    types: [
      'Public',
    ],
  },
  {
    date: '2022-07-15',
    localName: 'Demokrasi Bayramı',
    name: 'Democracy Day',
    countryCode: 'TR',
    fixed: true,
    global: true,
    counties: null,
    launchYear: null,
    types: [
      'Public',
    ],
  },
  {
    date: '2022-08-30',
    localName: 'Zafer Bayramı',
    name: 'Victory Day',
    countryCode: 'TR',
    fixed: true,
    global: true,
    counties: null,
    launchYear: null,
    types: [
      'Public',
    ],
  },
  {
    date: '2022-10-29',
    localName: 'Cumhuriyet Bayramı',
    name: 'Republic Day',
    countryCode: 'TR',
    fixed: true,
    global: true,
    counties: null,
    launchYear: null,
    types: [
      'Public',
    ],
  },
];
export default countryDetailsTestData;
